# Generated by Django 5.1 on 2024-09-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CID", "0002_accountrequest_authenticationform_searchitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmitMaintTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("platform", models.CharField(max_length=150)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("entered", "Entered"),
                        ],
                        default="submitted",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
